// Generated by gencpp from file deepsky/ExecuteResponse.msg
// DO NOT EDIT!


#ifndef DEEPSKY_MESSAGE_EXECUTERESPONSE_H
#define DEEPSKY_MESSAGE_EXECUTERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace deepsky
{
template <class ContainerAllocator>
struct ExecuteResponse_
{
  typedef ExecuteResponse_<ContainerAllocator> Type;

  ExecuteResponse_()
    : output()
    , code(0)  {
    }
  ExecuteResponse_(const ContainerAllocator& _alloc)
    : output(_alloc)
    , code(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _output_type;
  _output_type output;

   typedef int32_t _code_type;
  _code_type code;





  typedef boost::shared_ptr< ::deepsky::ExecuteResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::deepsky::ExecuteResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ExecuteResponse_

typedef ::deepsky::ExecuteResponse_<std::allocator<void> > ExecuteResponse;

typedef boost::shared_ptr< ::deepsky::ExecuteResponse > ExecuteResponsePtr;
typedef boost::shared_ptr< ::deepsky::ExecuteResponse const> ExecuteResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::deepsky::ExecuteResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::deepsky::ExecuteResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::deepsky::ExecuteResponse_<ContainerAllocator1> & lhs, const ::deepsky::ExecuteResponse_<ContainerAllocator2> & rhs)
{
  return lhs.output == rhs.output &&
    lhs.code == rhs.code;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::deepsky::ExecuteResponse_<ContainerAllocator1> & lhs, const ::deepsky::ExecuteResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace deepsky

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::deepsky::ExecuteResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::deepsky::ExecuteResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::deepsky::ExecuteResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::deepsky::ExecuteResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::deepsky::ExecuteResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::deepsky::ExecuteResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::deepsky::ExecuteResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d5b7f2e72c451a920e3fbb15b93f01be";
  }

  static const char* value(const ::deepsky::ExecuteResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd5b7f2e72c451a92ULL;
  static const uint64_t static_value2 = 0x0e3fbb15b93f01beULL;
};

template<class ContainerAllocator>
struct DataType< ::deepsky::ExecuteResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "deepsky/ExecuteResponse";
  }

  static const char* value(const ::deepsky::ExecuteResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::deepsky::ExecuteResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string output\n"
"int32 code\n"
"\n"
;
  }

  static const char* value(const ::deepsky::ExecuteResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::deepsky::ExecuteResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.output);
      stream.next(m.code);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ExecuteResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::deepsky::ExecuteResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::deepsky::ExecuteResponse_<ContainerAllocator>& v)
  {
    s << indent << "output: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.output);
    s << indent << "code: ";
    Printer<int32_t>::stream(s, indent + "  ", v.code);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEEPSKY_MESSAGE_EXECUTERESPONSE_H
