// Generated by gencpp from file deepsky/Execute.msg
// DO NOT EDIT!


#ifndef DEEPSKY_MESSAGE_EXECUTE_H
#define DEEPSKY_MESSAGE_EXECUTE_H

#include <ros/service_traits.h>


#include <deepsky/ExecuteRequest.h>
#include <deepsky/ExecuteResponse.h>


namespace deepsky
{

struct Execute
{

typedef ExecuteRequest Request;
typedef ExecuteResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Execute
} // namespace deepsky


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::deepsky::Execute > {
  static const char* value()
  {
    return "39a6fda3761b984206ead71aea9c2751";
  }

  static const char* value(const ::deepsky::Execute&) { return value(); }
};

template<>
struct DataType< ::deepsky::Execute > {
  static const char* value()
  {
    return "deepsky/Execute";
  }

  static const char* value(const ::deepsky::Execute&) { return value(); }
};


// service_traits::MD5Sum< ::deepsky::ExecuteRequest> should match
// service_traits::MD5Sum< ::deepsky::Execute >
template<>
struct MD5Sum< ::deepsky::ExecuteRequest>
{
  static const char* value()
  {
    return MD5Sum< ::deepsky::Execute >::value();
  }
  static const char* value(const ::deepsky::ExecuteRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepsky::ExecuteRequest> should match
// service_traits::DataType< ::deepsky::Execute >
template<>
struct DataType< ::deepsky::ExecuteRequest>
{
  static const char* value()
  {
    return DataType< ::deepsky::Execute >::value();
  }
  static const char* value(const ::deepsky::ExecuteRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::deepsky::ExecuteResponse> should match
// service_traits::MD5Sum< ::deepsky::Execute >
template<>
struct MD5Sum< ::deepsky::ExecuteResponse>
{
  static const char* value()
  {
    return MD5Sum< ::deepsky::Execute >::value();
  }
  static const char* value(const ::deepsky::ExecuteResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepsky::ExecuteResponse> should match
// service_traits::DataType< ::deepsky::Execute >
template<>
struct DataType< ::deepsky::ExecuteResponse>
{
  static const char* value()
  {
    return DataType< ::deepsky::Execute >::value();
  }
  static const char* value(const ::deepsky::ExecuteResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEEPSKY_MESSAGE_EXECUTE_H
