// Generated by gencpp from file deepsky/GetTelemetry.msg
// DO NOT EDIT!


#ifndef DEEPSKY_MESSAGE_GETTELEMETRY_H
#define DEEPSKY_MESSAGE_GETTELEMETRY_H

#include <ros/service_traits.h>


#include <deepsky/GetTelemetryRequest.h>
#include <deepsky/GetTelemetryResponse.h>


namespace deepsky
{

struct GetTelemetry
{

typedef GetTelemetryRequest Request;
typedef GetTelemetryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetTelemetry
} // namespace deepsky


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::deepsky::GetTelemetry > {
  static const char* value()
  {
    return "d674bf48285301c4b4e5e6f0893fc5e3";
  }

  static const char* value(const ::deepsky::GetTelemetry&) { return value(); }
};

template<>
struct DataType< ::deepsky::GetTelemetry > {
  static const char* value()
  {
    return "deepsky/GetTelemetry";
  }

  static const char* value(const ::deepsky::GetTelemetry&) { return value(); }
};


// service_traits::MD5Sum< ::deepsky::GetTelemetryRequest> should match
// service_traits::MD5Sum< ::deepsky::GetTelemetry >
template<>
struct MD5Sum< ::deepsky::GetTelemetryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::deepsky::GetTelemetry >::value();
  }
  static const char* value(const ::deepsky::GetTelemetryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepsky::GetTelemetryRequest> should match
// service_traits::DataType< ::deepsky::GetTelemetry >
template<>
struct DataType< ::deepsky::GetTelemetryRequest>
{
  static const char* value()
  {
    return DataType< ::deepsky::GetTelemetry >::value();
  }
  static const char* value(const ::deepsky::GetTelemetryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::deepsky::GetTelemetryResponse> should match
// service_traits::MD5Sum< ::deepsky::GetTelemetry >
template<>
struct MD5Sum< ::deepsky::GetTelemetryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::deepsky::GetTelemetry >::value();
  }
  static const char* value(const ::deepsky::GetTelemetryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepsky::GetTelemetryResponse> should match
// service_traits::DataType< ::deepsky::GetTelemetry >
template<>
struct DataType< ::deepsky::GetTelemetryResponse>
{
  static const char* value()
  {
    return DataType< ::deepsky::GetTelemetry >::value();
  }
  static const char* value(const ::deepsky::GetTelemetryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEEPSKY_MESSAGE_GETTELEMETRY_H
