// Generated by gencpp from file deepsky/NavigateGlobal.msg
// DO NOT EDIT!


#ifndef DEEPSKY_MESSAGE_NAVIGATEGLOBAL_H
#define DEEPSKY_MESSAGE_NAVIGATEGLOBAL_H

#include <ros/service_traits.h>


#include <deepsky/NavigateGlobalRequest.h>
#include <deepsky/NavigateGlobalResponse.h>


namespace deepsky
{

struct NavigateGlobal
{

typedef NavigateGlobalRequest Request;
typedef NavigateGlobalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct NavigateGlobal
} // namespace deepsky


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::deepsky::NavigateGlobal > {
  static const char* value()
  {
    return "56689871f219b2decd546e95f11e27a0";
  }

  static const char* value(const ::deepsky::NavigateGlobal&) { return value(); }
};

template<>
struct DataType< ::deepsky::NavigateGlobal > {
  static const char* value()
  {
    return "deepsky/NavigateGlobal";
  }

  static const char* value(const ::deepsky::NavigateGlobal&) { return value(); }
};


// service_traits::MD5Sum< ::deepsky::NavigateGlobalRequest> should match
// service_traits::MD5Sum< ::deepsky::NavigateGlobal >
template<>
struct MD5Sum< ::deepsky::NavigateGlobalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::deepsky::NavigateGlobal >::value();
  }
  static const char* value(const ::deepsky::NavigateGlobalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepsky::NavigateGlobalRequest> should match
// service_traits::DataType< ::deepsky::NavigateGlobal >
template<>
struct DataType< ::deepsky::NavigateGlobalRequest>
{
  static const char* value()
  {
    return DataType< ::deepsky::NavigateGlobal >::value();
  }
  static const char* value(const ::deepsky::NavigateGlobalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::deepsky::NavigateGlobalResponse> should match
// service_traits::MD5Sum< ::deepsky::NavigateGlobal >
template<>
struct MD5Sum< ::deepsky::NavigateGlobalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::deepsky::NavigateGlobal >::value();
  }
  static const char* value(const ::deepsky::NavigateGlobalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepsky::NavigateGlobalResponse> should match
// service_traits::DataType< ::deepsky::NavigateGlobal >
template<>
struct DataType< ::deepsky::NavigateGlobalResponse>
{
  static const char* value()
  {
    return DataType< ::deepsky::NavigateGlobal >::value();
  }
  static const char* value(const ::deepsky::NavigateGlobalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEEPSKY_MESSAGE_NAVIGATEGLOBAL_H
