// Generated by gencpp from file deepsky/SetAltitudeRequest.msg
// DO NOT EDIT!


#ifndef DEEPSKY_MESSAGE_SETALTITUDEREQUEST_H
#define DEEPSKY_MESSAGE_SETALTITUDEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace deepsky
{
template <class ContainerAllocator>
struct SetAltitudeRequest_
{
  typedef SetAltitudeRequest_<ContainerAllocator> Type;

  SetAltitudeRequest_()
    : z(0.0)
    , frame_id()  {
    }
  SetAltitudeRequest_(const ContainerAllocator& _alloc)
    : z(0.0)
    , frame_id(_alloc)  {
  (void)_alloc;
    }



   typedef float _z_type;
  _z_type z;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _frame_id_type;
  _frame_id_type frame_id;





  typedef boost::shared_ptr< ::deepsky::SetAltitudeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::deepsky::SetAltitudeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetAltitudeRequest_

typedef ::deepsky::SetAltitudeRequest_<std::allocator<void> > SetAltitudeRequest;

typedef boost::shared_ptr< ::deepsky::SetAltitudeRequest > SetAltitudeRequestPtr;
typedef boost::shared_ptr< ::deepsky::SetAltitudeRequest const> SetAltitudeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::deepsky::SetAltitudeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::deepsky::SetAltitudeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::deepsky::SetAltitudeRequest_<ContainerAllocator1> & lhs, const ::deepsky::SetAltitudeRequest_<ContainerAllocator2> & rhs)
{
  return lhs.z == rhs.z &&
    lhs.frame_id == rhs.frame_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::deepsky::SetAltitudeRequest_<ContainerAllocator1> & lhs, const ::deepsky::SetAltitudeRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace deepsky

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::deepsky::SetAltitudeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::deepsky::SetAltitudeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::deepsky::SetAltitudeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::deepsky::SetAltitudeRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::deepsky::SetAltitudeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::deepsky::SetAltitudeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::deepsky::SetAltitudeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3b21aa1342881379ae1c7a4b1071d4b3";
  }

  static const char* value(const ::deepsky::SetAltitudeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3b21aa1342881379ULL;
  static const uint64_t static_value2 = 0xae1c7a4b1071d4b3ULL;
};

template<class ContainerAllocator>
struct DataType< ::deepsky::SetAltitudeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "deepsky/SetAltitudeRequest";
  }

  static const char* value(const ::deepsky::SetAltitudeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::deepsky::SetAltitudeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 z\n"
"string frame_id\n"
;
  }

  static const char* value(const ::deepsky::SetAltitudeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::deepsky::SetAltitudeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.z);
      stream.next(m.frame_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetAltitudeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::deepsky::SetAltitudeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::deepsky::SetAltitudeRequest_<ContainerAllocator>& v)
  {
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "frame_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.frame_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEEPSKY_MESSAGE_SETALTITUDEREQUEST_H
