// Generated by gencpp from file deepsky/SetAltitude.msg
// DO NOT EDIT!


#ifndef DEEPSKY_MESSAGE_SETALTITUDE_H
#define DEEPSKY_MESSAGE_SETALTITUDE_H

#include <ros/service_traits.h>


#include <deepsky/SetAltitudeRequest.h>
#include <deepsky/SetAltitudeResponse.h>


namespace deepsky
{

struct SetAltitude
{

typedef SetAltitudeRequest Request;
typedef SetAltitudeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetAltitude
} // namespace deepsky


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::deepsky::SetAltitude > {
  static const char* value()
  {
    return "3156c628a6aee1d23a3fc3177b7fa0dd";
  }

  static const char* value(const ::deepsky::SetAltitude&) { return value(); }
};

template<>
struct DataType< ::deepsky::SetAltitude > {
  static const char* value()
  {
    return "deepsky/SetAltitude";
  }

  static const char* value(const ::deepsky::SetAltitude&) { return value(); }
};


// service_traits::MD5Sum< ::deepsky::SetAltitudeRequest> should match
// service_traits::MD5Sum< ::deepsky::SetAltitude >
template<>
struct MD5Sum< ::deepsky::SetAltitudeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::deepsky::SetAltitude >::value();
  }
  static const char* value(const ::deepsky::SetAltitudeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepsky::SetAltitudeRequest> should match
// service_traits::DataType< ::deepsky::SetAltitude >
template<>
struct DataType< ::deepsky::SetAltitudeRequest>
{
  static const char* value()
  {
    return DataType< ::deepsky::SetAltitude >::value();
  }
  static const char* value(const ::deepsky::SetAltitudeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::deepsky::SetAltitudeResponse> should match
// service_traits::MD5Sum< ::deepsky::SetAltitude >
template<>
struct MD5Sum< ::deepsky::SetAltitudeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::deepsky::SetAltitude >::value();
  }
  static const char* value(const ::deepsky::SetAltitudeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepsky::SetAltitudeResponse> should match
// service_traits::DataType< ::deepsky::SetAltitude >
template<>
struct DataType< ::deepsky::SetAltitudeResponse>
{
  static const char* value()
  {
    return DataType< ::deepsky::SetAltitude >::value();
  }
  static const char* value(const ::deepsky::SetAltitudeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEEPSKY_MESSAGE_SETALTITUDE_H
