// Generated by gencpp from file deepsky/SetAttitude.msg
// DO NOT EDIT!


#ifndef DEEPSKY_MESSAGE_SETATTITUDE_H
#define DEEPSKY_MESSAGE_SETATTITUDE_H

#include <ros/service_traits.h>


#include <deepsky/SetAttitudeRequest.h>
#include <deepsky/SetAttitudeResponse.h>


namespace deepsky
{

struct SetAttitude
{

typedef SetAttitudeRequest Request;
typedef SetAttitudeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetAttitude
} // namespace deepsky


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::deepsky::SetAttitude > {
  static const char* value()
  {
    return "7128859bdc91bd3cc6b04ddd6dc5c060";
  }

  static const char* value(const ::deepsky::SetAttitude&) { return value(); }
};

template<>
struct DataType< ::deepsky::SetAttitude > {
  static const char* value()
  {
    return "deepsky/SetAttitude";
  }

  static const char* value(const ::deepsky::SetAttitude&) { return value(); }
};


// service_traits::MD5Sum< ::deepsky::SetAttitudeRequest> should match
// service_traits::MD5Sum< ::deepsky::SetAttitude >
template<>
struct MD5Sum< ::deepsky::SetAttitudeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::deepsky::SetAttitude >::value();
  }
  static const char* value(const ::deepsky::SetAttitudeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepsky::SetAttitudeRequest> should match
// service_traits::DataType< ::deepsky::SetAttitude >
template<>
struct DataType< ::deepsky::SetAttitudeRequest>
{
  static const char* value()
  {
    return DataType< ::deepsky::SetAttitude >::value();
  }
  static const char* value(const ::deepsky::SetAttitudeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::deepsky::SetAttitudeResponse> should match
// service_traits::MD5Sum< ::deepsky::SetAttitude >
template<>
struct MD5Sum< ::deepsky::SetAttitudeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::deepsky::SetAttitude >::value();
  }
  static const char* value(const ::deepsky::SetAttitudeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepsky::SetAttitudeResponse> should match
// service_traits::DataType< ::deepsky::SetAttitude >
template<>
struct DataType< ::deepsky::SetAttitudeResponse>
{
  static const char* value()
  {
    return DataType< ::deepsky::SetAttitude >::value();
  }
  static const char* value(const ::deepsky::SetAttitudeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEEPSKY_MESSAGE_SETATTITUDE_H
