// Generated by gencpp from file deepsky/SetPosition.msg
// DO NOT EDIT!


#ifndef DEEPSKY_MESSAGE_SETPOSITION_H
#define DEEPSKY_MESSAGE_SETPOSITION_H

#include <ros/service_traits.h>


#include <deepsky/SetPositionRequest.h>
#include <deepsky/SetPositionResponse.h>


namespace deepsky
{

struct SetPosition
{

typedef SetPositionRequest Request;
typedef SetPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPosition
} // namespace deepsky


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::deepsky::SetPosition > {
  static const char* value()
  {
    return "83786a334e74ec5b9b5b37278c018807";
  }

  static const char* value(const ::deepsky::SetPosition&) { return value(); }
};

template<>
struct DataType< ::deepsky::SetPosition > {
  static const char* value()
  {
    return "deepsky/SetPosition";
  }

  static const char* value(const ::deepsky::SetPosition&) { return value(); }
};


// service_traits::MD5Sum< ::deepsky::SetPositionRequest> should match
// service_traits::MD5Sum< ::deepsky::SetPosition >
template<>
struct MD5Sum< ::deepsky::SetPositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::deepsky::SetPosition >::value();
  }
  static const char* value(const ::deepsky::SetPositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepsky::SetPositionRequest> should match
// service_traits::DataType< ::deepsky::SetPosition >
template<>
struct DataType< ::deepsky::SetPositionRequest>
{
  static const char* value()
  {
    return DataType< ::deepsky::SetPosition >::value();
  }
  static const char* value(const ::deepsky::SetPositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::deepsky::SetPositionResponse> should match
// service_traits::MD5Sum< ::deepsky::SetPosition >
template<>
struct MD5Sum< ::deepsky::SetPositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::deepsky::SetPosition >::value();
  }
  static const char* value(const ::deepsky::SetPositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepsky::SetPositionResponse> should match
// service_traits::DataType< ::deepsky::SetPosition >
template<>
struct DataType< ::deepsky::SetPositionResponse>
{
  static const char* value()
  {
    return DataType< ::deepsky::SetPosition >::value();
  }
  static const char* value(const ::deepsky::SetPositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEEPSKY_MESSAGE_SETPOSITION_H
