// Generated by gencpp from file deepsky/SetRates.msg
// DO NOT EDIT!


#ifndef DEEPSKY_MESSAGE_SETRATES_H
#define DEEPSKY_MESSAGE_SETRATES_H

#include <ros/service_traits.h>


#include <deepsky/SetRatesRequest.h>
#include <deepsky/SetRatesResponse.h>


namespace deepsky
{

struct SetRates
{

typedef SetRatesRequest Request;
typedef SetRatesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetRates
} // namespace deepsky


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::deepsky::SetRates > {
  static const char* value()
  {
    return "ccbfa7cdb7afa9d02e4d42a934ca130e";
  }

  static const char* value(const ::deepsky::SetRates&) { return value(); }
};

template<>
struct DataType< ::deepsky::SetRates > {
  static const char* value()
  {
    return "deepsky/SetRates";
  }

  static const char* value(const ::deepsky::SetRates&) { return value(); }
};


// service_traits::MD5Sum< ::deepsky::SetRatesRequest> should match
// service_traits::MD5Sum< ::deepsky::SetRates >
template<>
struct MD5Sum< ::deepsky::SetRatesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::deepsky::SetRates >::value();
  }
  static const char* value(const ::deepsky::SetRatesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepsky::SetRatesRequest> should match
// service_traits::DataType< ::deepsky::SetRates >
template<>
struct DataType< ::deepsky::SetRatesRequest>
{
  static const char* value()
  {
    return DataType< ::deepsky::SetRates >::value();
  }
  static const char* value(const ::deepsky::SetRatesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::deepsky::SetRatesResponse> should match
// service_traits::MD5Sum< ::deepsky::SetRates >
template<>
struct MD5Sum< ::deepsky::SetRatesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::deepsky::SetRates >::value();
  }
  static const char* value(const ::deepsky::SetRatesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepsky::SetRatesResponse> should match
// service_traits::DataType< ::deepsky::SetRates >
template<>
struct DataType< ::deepsky::SetRatesResponse>
{
  static const char* value()
  {
    return DataType< ::deepsky::SetRates >::value();
  }
  static const char* value(const ::deepsky::SetRatesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEEPSKY_MESSAGE_SETRATES_H
