// Generated by gencpp from file deepsky/SetVelocity.msg
// DO NOT EDIT!


#ifndef DEEPSKY_MESSAGE_SETVELOCITY_H
#define DEEPSKY_MESSAGE_SETVELOCITY_H

#include <ros/service_traits.h>


#include <deepsky/SetVelocityRequest.h>
#include <deepsky/SetVelocityResponse.h>


namespace deepsky
{

struct SetVelocity
{

typedef SetVelocityRequest Request;
typedef SetVelocityResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetVelocity
} // namespace deepsky


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::deepsky::SetVelocity > {
  static const char* value()
  {
    return "150892103e4e5bde394f7e522da84e25";
  }

  static const char* value(const ::deepsky::SetVelocity&) { return value(); }
};

template<>
struct DataType< ::deepsky::SetVelocity > {
  static const char* value()
  {
    return "deepsky/SetVelocity";
  }

  static const char* value(const ::deepsky::SetVelocity&) { return value(); }
};


// service_traits::MD5Sum< ::deepsky::SetVelocityRequest> should match
// service_traits::MD5Sum< ::deepsky::SetVelocity >
template<>
struct MD5Sum< ::deepsky::SetVelocityRequest>
{
  static const char* value()
  {
    return MD5Sum< ::deepsky::SetVelocity >::value();
  }
  static const char* value(const ::deepsky::SetVelocityRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepsky::SetVelocityRequest> should match
// service_traits::DataType< ::deepsky::SetVelocity >
template<>
struct DataType< ::deepsky::SetVelocityRequest>
{
  static const char* value()
  {
    return DataType< ::deepsky::SetVelocity >::value();
  }
  static const char* value(const ::deepsky::SetVelocityRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::deepsky::SetVelocityResponse> should match
// service_traits::MD5Sum< ::deepsky::SetVelocity >
template<>
struct MD5Sum< ::deepsky::SetVelocityResponse>
{
  static const char* value()
  {
    return MD5Sum< ::deepsky::SetVelocity >::value();
  }
  static const char* value(const ::deepsky::SetVelocityResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepsky::SetVelocityResponse> should match
// service_traits::DataType< ::deepsky::SetVelocity >
template<>
struct DataType< ::deepsky::SetVelocityResponse>
{
  static const char* value()
  {
    return DataType< ::deepsky::SetVelocity >::value();
  }
  static const char* value(const ::deepsky::SetVelocityResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEEPSKY_MESSAGE_SETVELOCITY_H
