// Generated by gencpp from file deepsky/SetYaw.msg
// DO NOT EDIT!


#ifndef DEEPSKY_MESSAGE_SETYAW_H
#define DEEPSKY_MESSAGE_SETYAW_H

#include <ros/service_traits.h>


#include <deepsky/SetYawRequest.h>
#include <deepsky/SetYawResponse.h>


namespace deepsky
{

struct SetYaw
{

typedef SetYawRequest Request;
typedef SetYawResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetYaw
} // namespace deepsky


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::deepsky::SetYaw > {
  static const char* value()
  {
    return "8e1005e0652136b0ffee84fd89127463";
  }

  static const char* value(const ::deepsky::SetYaw&) { return value(); }
};

template<>
struct DataType< ::deepsky::SetYaw > {
  static const char* value()
  {
    return "deepsky/SetYaw";
  }

  static const char* value(const ::deepsky::SetYaw&) { return value(); }
};


// service_traits::MD5Sum< ::deepsky::SetYawRequest> should match
// service_traits::MD5Sum< ::deepsky::SetYaw >
template<>
struct MD5Sum< ::deepsky::SetYawRequest>
{
  static const char* value()
  {
    return MD5Sum< ::deepsky::SetYaw >::value();
  }
  static const char* value(const ::deepsky::SetYawRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepsky::SetYawRequest> should match
// service_traits::DataType< ::deepsky::SetYaw >
template<>
struct DataType< ::deepsky::SetYawRequest>
{
  static const char* value()
  {
    return DataType< ::deepsky::SetYaw >::value();
  }
  static const char* value(const ::deepsky::SetYawRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::deepsky::SetYawResponse> should match
// service_traits::MD5Sum< ::deepsky::SetYaw >
template<>
struct MD5Sum< ::deepsky::SetYawResponse>
{
  static const char* value()
  {
    return MD5Sum< ::deepsky::SetYaw >::value();
  }
  static const char* value(const ::deepsky::SetYawResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepsky::SetYawResponse> should match
// service_traits::DataType< ::deepsky::SetYaw >
template<>
struct DataType< ::deepsky::SetYawResponse>
{
  static const char* value()
  {
    return DataType< ::deepsky::SetYaw >::value();
  }
  static const char* value(const ::deepsky::SetYawResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEEPSKY_MESSAGE_SETYAW_H
