// Generated by gencpp from file deepsky/SetYawRate.msg
// DO NOT EDIT!


#ifndef DEEPSKY_MESSAGE_SETYAWRATE_H
#define DEEPSKY_MESSAGE_SETYAWRATE_H

#include <ros/service_traits.h>


#include <deepsky/SetYawRateRequest.h>
#include <deepsky/SetYawRateResponse.h>


namespace deepsky
{

struct SetYawRate
{

typedef SetYawRateRequest Request;
typedef SetYawRateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetYawRate
} // namespace deepsky


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::deepsky::SetYawRate > {
  static const char* value()
  {
    return "e84dd53db872d0c7a7d675a20e28c95f";
  }

  static const char* value(const ::deepsky::SetYawRate&) { return value(); }
};

template<>
struct DataType< ::deepsky::SetYawRate > {
  static const char* value()
  {
    return "deepsky/SetYawRate";
  }

  static const char* value(const ::deepsky::SetYawRate&) { return value(); }
};


// service_traits::MD5Sum< ::deepsky::SetYawRateRequest> should match
// service_traits::MD5Sum< ::deepsky::SetYawRate >
template<>
struct MD5Sum< ::deepsky::SetYawRateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::deepsky::SetYawRate >::value();
  }
  static const char* value(const ::deepsky::SetYawRateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepsky::SetYawRateRequest> should match
// service_traits::DataType< ::deepsky::SetYawRate >
template<>
struct DataType< ::deepsky::SetYawRateRequest>
{
  static const char* value()
  {
    return DataType< ::deepsky::SetYawRate >::value();
  }
  static const char* value(const ::deepsky::SetYawRateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::deepsky::SetYawRateResponse> should match
// service_traits::MD5Sum< ::deepsky::SetYawRate >
template<>
struct MD5Sum< ::deepsky::SetYawRateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::deepsky::SetYawRate >::value();
  }
  static const char* value(const ::deepsky::SetYawRateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepsky::SetYawRateResponse> should match
// service_traits::DataType< ::deepsky::SetYawRate >
template<>
struct DataType< ::deepsky::SetYawRateResponse>
{
  static const char* value()
  {
    return DataType< ::deepsky::SetYawRate >::value();
  }
  static const char* value(const ::deepsky::SetYawRateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEEPSKY_MESSAGE_SETYAWRATE_H
