// Generated by gencpp from file deepsky_blocks/Load.msg
// DO NOT EDIT!


#ifndef DEEPSKY_BLOCKS_MESSAGE_LOAD_H
#define DEEPSKY_BLOCKS_MESSAGE_LOAD_H

#include <ros/service_traits.h>


#include <deepsky_blocks/LoadRequest.h>
#include <deepsky_blocks/LoadResponse.h>


namespace deepsky_blocks
{

struct Load
{

typedef LoadRequest Request;
typedef LoadResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Load
} // namespace deepsky_blocks


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::deepsky_blocks::Load > {
  static const char* value()
  {
    return "591c1a24e79f31bc423b909d1e92af1b";
  }

  static const char* value(const ::deepsky_blocks::Load&) { return value(); }
};

template<>
struct DataType< ::deepsky_blocks::Load > {
  static const char* value()
  {
    return "deepsky_blocks/Load";
  }

  static const char* value(const ::deepsky_blocks::Load&) { return value(); }
};


// service_traits::MD5Sum< ::deepsky_blocks::LoadRequest> should match
// service_traits::MD5Sum< ::deepsky_blocks::Load >
template<>
struct MD5Sum< ::deepsky_blocks::LoadRequest>
{
  static const char* value()
  {
    return MD5Sum< ::deepsky_blocks::Load >::value();
  }
  static const char* value(const ::deepsky_blocks::LoadRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepsky_blocks::LoadRequest> should match
// service_traits::DataType< ::deepsky_blocks::Load >
template<>
struct DataType< ::deepsky_blocks::LoadRequest>
{
  static const char* value()
  {
    return DataType< ::deepsky_blocks::Load >::value();
  }
  static const char* value(const ::deepsky_blocks::LoadRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::deepsky_blocks::LoadResponse> should match
// service_traits::MD5Sum< ::deepsky_blocks::Load >
template<>
struct MD5Sum< ::deepsky_blocks::LoadResponse>
{
  static const char* value()
  {
    return MD5Sum< ::deepsky_blocks::Load >::value();
  }
  static const char* value(const ::deepsky_blocks::LoadResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepsky_blocks::LoadResponse> should match
// service_traits::DataType< ::deepsky_blocks::Load >
template<>
struct DataType< ::deepsky_blocks::LoadResponse>
{
  static const char* value()
  {
    return DataType< ::deepsky_blocks::Load >::value();
  }
  static const char* value(const ::deepsky_blocks::LoadResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEEPSKY_BLOCKS_MESSAGE_LOAD_H
