// Generated by gencpp from file deepsky_blocks/Run.msg
// DO NOT EDIT!


#ifndef DEEPSKY_BLOCKS_MESSAGE_RUN_H
#define DEEPSKY_BLOCKS_MESSAGE_RUN_H

#include <ros/service_traits.h>


#include <deepsky_blocks/RunRequest.h>
#include <deepsky_blocks/RunResponse.h>


namespace deepsky_blocks
{

struct Run
{

typedef RunRequest Request;
typedef RunResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Run
} // namespace deepsky_blocks


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::deepsky_blocks::Run > {
  static const char* value()
  {
    return "c0a76d801e7d5147feb773127182d76c";
  }

  static const char* value(const ::deepsky_blocks::Run&) { return value(); }
};

template<>
struct DataType< ::deepsky_blocks::Run > {
  static const char* value()
  {
    return "deepsky_blocks/Run";
  }

  static const char* value(const ::deepsky_blocks::Run&) { return value(); }
};


// service_traits::MD5Sum< ::deepsky_blocks::RunRequest> should match
// service_traits::MD5Sum< ::deepsky_blocks::Run >
template<>
struct MD5Sum< ::deepsky_blocks::RunRequest>
{
  static const char* value()
  {
    return MD5Sum< ::deepsky_blocks::Run >::value();
  }
  static const char* value(const ::deepsky_blocks::RunRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepsky_blocks::RunRequest> should match
// service_traits::DataType< ::deepsky_blocks::Run >
template<>
struct DataType< ::deepsky_blocks::RunRequest>
{
  static const char* value()
  {
    return DataType< ::deepsky_blocks::Run >::value();
  }
  static const char* value(const ::deepsky_blocks::RunRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::deepsky_blocks::RunResponse> should match
// service_traits::MD5Sum< ::deepsky_blocks::Run >
template<>
struct MD5Sum< ::deepsky_blocks::RunResponse>
{
  static const char* value()
  {
    return MD5Sum< ::deepsky_blocks::Run >::value();
  }
  static const char* value(const ::deepsky_blocks::RunResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepsky_blocks::RunResponse> should match
// service_traits::DataType< ::deepsky_blocks::Run >
template<>
struct DataType< ::deepsky_blocks::RunResponse>
{
  static const char* value()
  {
    return DataType< ::deepsky_blocks::Run >::value();
  }
  static const char* value(const ::deepsky_blocks::RunResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEEPSKY_BLOCKS_MESSAGE_RUN_H
