// Generated by gencpp from file deepsky_blocks/Store.msg
// DO NOT EDIT!


#ifndef DEEPSKY_BLOCKS_MESSAGE_STORE_H
#define DEEPSKY_BLOCKS_MESSAGE_STORE_H

#include <ros/service_traits.h>


#include <deepsky_blocks/StoreRequest.h>
#include <deepsky_blocks/StoreResponse.h>


namespace deepsky_blocks
{

struct Store
{

typedef StoreRequest Request;
typedef StoreResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Store
} // namespace deepsky_blocks


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::deepsky_blocks::Store > {
  static const char* value()
  {
    return "9e64eeb2e84c0420f3367c9e49c7fa5e";
  }

  static const char* value(const ::deepsky_blocks::Store&) { return value(); }
};

template<>
struct DataType< ::deepsky_blocks::Store > {
  static const char* value()
  {
    return "deepsky_blocks/Store";
  }

  static const char* value(const ::deepsky_blocks::Store&) { return value(); }
};


// service_traits::MD5Sum< ::deepsky_blocks::StoreRequest> should match
// service_traits::MD5Sum< ::deepsky_blocks::Store >
template<>
struct MD5Sum< ::deepsky_blocks::StoreRequest>
{
  static const char* value()
  {
    return MD5Sum< ::deepsky_blocks::Store >::value();
  }
  static const char* value(const ::deepsky_blocks::StoreRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepsky_blocks::StoreRequest> should match
// service_traits::DataType< ::deepsky_blocks::Store >
template<>
struct DataType< ::deepsky_blocks::StoreRequest>
{
  static const char* value()
  {
    return DataType< ::deepsky_blocks::Store >::value();
  }
  static const char* value(const ::deepsky_blocks::StoreRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::deepsky_blocks::StoreResponse> should match
// service_traits::MD5Sum< ::deepsky_blocks::Store >
template<>
struct MD5Sum< ::deepsky_blocks::StoreResponse>
{
  static const char* value()
  {
    return MD5Sum< ::deepsky_blocks::Store >::value();
  }
  static const char* value(const ::deepsky_blocks::StoreResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepsky_blocks::StoreResponse> should match
// service_traits::DataType< ::deepsky_blocks::Store >
template<>
struct DataType< ::deepsky_blocks::StoreResponse>
{
  static const char* value()
  {
    return DataType< ::deepsky_blocks::Store >::value();
  }
  static const char* value(const ::deepsky_blocks::StoreResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEEPSKY_BLOCKS_MESSAGE_STORE_H
